solve 03-UiInput in 06-wrappers, redo 03-UiButton in 06-wrappers
js-tasks-ru/vue-20231109_d-a-fayl pull request #10
Opened 2023-12-13 06:51 UTC by dfajl

Григорий, доброго дня!

Вопрос 1: 
**$refs['firstInput'].$refs['input']** - синтаксис такого рода - это техническое требование или предпочтение разработчика / требование командного стиля? 
Насколько я знаю, мы обязаны заключать поля объектов в квадратные скобки, если имя свойства не является одним словом, н-ер, **first-input / first input**.

Вопрос 2:
Насколько правильно решен пункт с **v-model.lazy**?
Единственный способ избежать проблем с "полуреактивностью" $attr - это записать логику в методы?
Насколько корректно прям в шаблоне использовать вызов функции для получения имени динамического атрибута события change / input?

2023-12-13 06:52 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-13 21:49 UTC, ShGKme requested changes

2023-12-13 21:49 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    },
Этот метод явно вычисляет значение на основе состояние компонента и лучше его делать именно вычисляемым свойством. Нам не требуется делать это вычисление каждый раз при рендеринге.

2023-12-13 21:49 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    },
В то же время модификаторы модули не должны быть использованы как атрибут. В целом, если требуется писать какую-то логику в компоненте в зависимости от какого-то конкретного атрибута — то он должен уже быть не атрибутом, а именно параметром компонента, так как определяет его работу. `$attrs` должен использоваться только для передачи его куда-то целиком, в крайнем случае с какой-то фильтрацией.

Но `modelModifiers` однозначно должен быть именно параметром, это стандартный параметр для работы с `v-model`.

2023-12-13 21:52 UTC, ShGKme commented
> **$refs['firstInput'].$refs['input']** - синтаксис такого рода - это техническое требование или предпочтение разработчика / требование командного стиля?
> Насколько я знаю, мы обязаны заключать поля объектов в квадратные скобки, если имя свойства не является одним словом, н-ер, **first-input / first input**.

Вопрос стиля. Например, есть подход, когда обращаются через `['']` в тех случаях, когда в объекте не известен заранее набор полей. Например, в объекте митапа мы точно знаем, какие должны быть поля, это конкретная структура. Обращаемся через точку. А здесь - `$refs` используется как структура ключ-значение для работы по любому ключу. Такая запись может помочь подчеркнуть это. Но это исключительно вопрос стиля.

Раньше я придерживался такого стиля, и в не самых новых материалах и примерах он остался

2023-12-13 21:52 UTC, ShGKme commented
> Насколько правильно решен пункт с **v-model.lazy**?
> Единственный способ избежать проблем с "полуреактивностью" $attr - это записать логику в методы?

Написал в ревью

2023-12-13 21:53 UTC, ShGKme commented
> Вопрос 3:
> Больше философский вопрос!
> Зачем вообще Vue сделал модификатор lazy, который не работает "из коробки"? Это их баг и его планируется решить в следующих релизах?
> Или здесь есть какой-то технический подвох, что они поступили таким способом?

На нативных элементах, где сам Vue определяет, как именно работает `v-model` - он работает из коробки.

Но в компонентах мы сами определяем, что такое `v-model`, и как он работает. Здесь Vue просто не может сделать это за нас, так как мы сами контролируем, когда и как порождается событие обновление модели. У Vue нет технической возможности за нас переопределить, какое именно событие слушать на `input`.

2023-12-14 07:36 UTC, dfajl commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    },
Не совсем понял, как реализовать modelModifiers в качестве параметра. Он ведь не передан как пропс. Или вы имеете ввиду в data поместить его, а потом делать вычисляемое свойство?

2023-12-14 07:58 UTC, dfajl commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    },
и еще один вопрос: если бы даже $attrs был совсем не реактивный (допустим, мы используем composition), то в случаях, когда надо просто определить: как рендерить экземпляр компонента - мы можем использовать computed?

Если да, то почему тогда здесь вы написали, что computed не сработает в composition API?
![image](https://github.com/js-tasks-ru/vue-20231109_d-a-fayl/assets/75556674/91570ca1-e00b-46fe-a7b1-1e905b30b7f0)

2023-12-14 22:41 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    },
> Не совсем понял, как реализовать modelModifiers в качестве параметра. Он ведь не передан как пропс. Или вы имеете ввиду в data поместить его, а потом делать вычисляемое свойство?

Явно определить его как `props`. Он будет передаваться как параметр компонента, так же как сейчас приходит в атрибуты (потому что не описан в props)

2023-12-14 22:43 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    },
> Ведь по сути, данное свойство уже никак не может быть изменено в процессе использования экземпляра. Т.е., отрисовали компонент 1 раз со всеми его атрибутами и больше они не поменяются ведь на протяжении всего жизненного цикла.

Хотя шаблон не позволяет легко динамически изменить модификаторы директивы, в общем случае это возможно (через рендер функцию, например).

В любом случае, лучше не работать с `$attrs`, как с реактивными данными, потому что они не являются в полной мере реактивными.

2023-12-15 05:34 UTC, dfajl commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    },
Кажется, понял вас)

2023-12-15 05:41 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-15 16:54 UTC, ShGKme approved these changes

2023-12-15 16:54 UTC, merged