solve 07-forms/01-CounterButtonComplete and 07-forms/02-MeetupForm/co…
js-tasks-ru/vue-20231109_d-a-fayl pull request #11
Opened 2023-12-18 06:06 UTC by dfajl

2023-12-18 06:07 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-18 06:23 UTC, dfajl commented
Григорий, приветствую!

Подскажите, пожалуйста, по задаче meetupForm.

Компонент **UiInput** компонента **meetup-agenda-item-form** принимает modelModifiers. **Computed** отдает событие **input**, т.к. **lazy === false**. Но, если посмотреть на обработчик UiInput - там слушается change. И в девтулзах тоже в поле event-listeners есть событие change с пометкой not declared. Т.е, несмотря на то, что мы сами определяем событие обновления модели через вычисляемое св-во, vue может дополнительно решить, что у **type="time"** еще может быть событие change и породить его при выборе времени?

Вопрос 2: 
![image](https://github.com/js-tasks-ru/vue-20231109_d-a-fayl/assets/75556674/06b9d552-9339-416c-92ea-7fdc06e2d344)

34 и 35ую строки так и хочется поменять на v-model. Но это не работает. Потому что директива v-model умеет только модель agenda-item обновить новым значением, а у нас там JS код, который работает не с моделью agenda-item?

2023-12-20 01:18 UTC, ShGKme requested changes

2023-12-20 01:18 UTC, ShGKme commented on 07-forms/01-CounterButtonComplete/components/CounterButton.vue
> +  },
Решение с вычисляемым свойством работает не совсем корректно. С ним родитель не может "обнулить" счётчик, сбросив его в 0, так как не пройдёт проверка на `if`.

2023-12-20 01:18 UTC, ShGKme commented on 07-forms/02-MeetupForm/components/MeetupForm.vue
> +            :preview="imageToUpload?.src || ''"
Начальное изображение находится в данных митапа - `meetup.image`

`imageToUpload` - это изображение для загрузки, то есть новый выбранный файл, который потребуется потом загрузить на сервер как файл, чтобы получить изображение на сервере с ссылкой на него.

2023-12-20 01:18 UTC, ShGKme commented on 07-forms/02-MeetupForm/components/MeetupForm.vue
> +    },
Здесь при добавлении пункта программы всегда добавляется в массив объект `this.agendaItem`. Но это всегда один объект. В итоге, если добавить в митап 5 пунктов программы, то все они будут ссылкой на один и тот же объект, и изменение времени начала в состоянии компонента — меняет время начала всех добавленных пунктов программы, которые ещё не были пересозданы.

При добавлении каждого пункта, данные для него должны создаваться заново, а не переиспользоваться ссылка на один объект.

При этом `agendaItem` не должно быть состоянием компонента в любом случае. У формы редактирования митапа нет "одного пункта программы". Есть данные митапа, которые уже включают в себя массив, и это массив с множеством пунктов программы, а не одним.

2023-12-20 01:26 UTC, ShGKme commented
> 34 и 35ую строки так и хочется поменять на v-model. Но это не работает. Потому что директива v-model умеет только модель agenda-item обновить новым значением, а у нас там JS код, который работает не с моделью agenda-item?
> Иными словами: v-model работал бы только в таком виде?
> **_:agenda-item="agendaItem" @update:agendaItem="agendaItem = $event"_**

Там можно использовать `v-model`, но при правильном значении.

Если использовать как
```html
<MeetupAgendaItemForm
  v-for="agendaItem in localmeetup.agenda"
  v-model="agendaItem"
/>
```

То модель устанавливается не на пункт программы в массиве программы, а на параметр цикла.

Такая модель работает как
```html
<MeetupAgendaItemForm
  v-for="agendaItem in localmeetup.agenda"
  :agenda-item="agendaItem"
  @update:agendaItem="agendaItem = $event"
/>
```

И приводит к некорректно работе именно потому, что не работает `agendaItem = $event`. 

`agendaItem` - это параметр цикла, то есть переменная, в которую JS положит значение из массива во время перебора массива. Аналог на JS мог бы быть:
```js
for (let agendaItem of localmeetup.agenda) {
  onUpdateAgendaItem = ($event) => {
    agendaItem = $event
  }
}
// или
for (let i = 0; i < localmeetup.agenda.length; i++) {
  let agendaItem = localmeetup.agenda[i]
  onUpdateAgendaItem = ($event) => {
    agendaItem = $event
  }
}
```

В обоих случаях присваивание значения в параметр цикла не приводит к изменению элементов массива.

Чтобы привязка работала - привязывать нужно именно элемент массива.

```html
<MeetupAgendaItemForm
  v-for="(agendaItem, index) in localMeetup.agenda"
  v-model="localMeetup.agenda[index]"
/>
```

Такая модель уже будет работать, так как работает как присваивание в элемент массива меняет массив, как в

```html
<MeetupAgendaItemForm
  v-for="(agendaItem, index) in localmeetup.agenda"
  :agenda-item="localMeetup.agenda[index]"
  @update:agendaItem="localMeetup.agenda[index] = $event"
/>
```

2023-12-20 01:32 UTC, ShGKme commented
> Компонент **UiInput** компонента **meetup-agenda-item-form** принимает modelModifiers. **Computed** отдает событие **input**, т.к. **lazy === false**. Но, если посмотреть на обработчик UiInput - там слушается change. И в девтулзах тоже в поле event-listeners есть событие change с пометкой not declared. Т.е, несмотря на то, что мы сами определяем событие обновления модели через вычисляемое св-во, vue может дополнительно решить, что у **type="time"** еще может быть событие change и породить его при выборе времени?

Этот вопрос не совсем понял.

Компонент `UiInput` порождает только событие обновление `update:modelValue`. Вне зависимости от `modelModifiers` всегда порождается именно это событие, а меняется только то, когда оно порождается, по какому событию инпута.

Обработчик события `change` передаётся на UiInput, но не как обработчик события компонента, а как обработчик нативного события, как атрибут в `$attrs`.

2023-12-21 05:57 UTC, dfajl commented
Не до конца понимаю ситуацию с @change в UiInput.

![image](https://github.com/js-tasks-ru/vue-20231109_d-a-fayl/assets/75556674/28f5c4fd-e3e7-4623-b91b-79de54b02b35)
А для чего тогда передавать модель **:model-value="agendaItem.startsAt"**? Если мы слушаем событие change нативного input внутри компонента MeetupAgendaItemForm, а компонент MeetupForm уже обновляет модель agendaItem.

Ведь, получается, что использование UiInput по сути и не нужно тут кроме как для того, чтобы использовать его стили.

2023-12-21 11:11 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-21 23:34 UTC, ShGKme approved these changes

2023-12-21 23:34 UTC, merged

2023-12-21 23:38 UTC, ShGKme commented
> А для чего тогда передавать модель **:model-value="agendaItem.startsAt"**? Если мы слушаем событие change нативного input внутри компонента MeetupAgendaItemForm

Передаваемые параметр и прослушивание события никак не влияют друг на друга.

Мы привязываем `model-value` у `UiInput` к `agendaItem.startsAt`, чтобы в поле ввода в качестве значения выводилось его значение — время начала. Вне зависимости от того, какое событие мы слушаем и вообще слушаем ли мы какое-то событие, нам нужно привязать значение поля ввода к введённому/начальному значению.

Если мы не будем привязывать `model-value`, то в поле ввода времени начала не будет отображаться это самое время начала.